name: CI/CD for petStoreProject

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup-environment:
    name: Set up Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # You can use other distributions like 'zulu' or 'adopt'
          java-version: '17'     # Change to the version your project uses

      - name: Set up Maven Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy Application
        run: |
          echo "Deployment step goes here"
          # Add deployment scripts here
